# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://ezrider.github.io/thrombo_cytosis/"

git_url = "https://github.com/ezrider/thrombo_cytosis/tree/{branch}/"

def custom_doc_links(name): return None
