# AUTOGENERATED! DO NOT EDIT! File to edit: 00_data.ipynb (unless otherwise specified).

__all__ = ['get_data']

# Cell
import pandas as pd
import altair as alt


# Cell
def get_data():
    df = pd.read_csv('./data/Szallasi_raw_data_final.csv' )
    return df